//let dataset = "AAAACCCGGT"
let dataset = "GGATTGCGCTACAGGCTTCCTAGGGTAAAAGCCATTGAGATTTAAGCAGGATTAGCCTTTCACACACGCGCCGATCTAAAGGTTGGCTAGTCGACGGCTCCTCTGACTCACAGCGCCTGCTCCAAATTTCATTATCTAGATAAAACCCCGGGACTTATGTAGTTCCTTCCACAGCATGTCCAGCTTTTCCTTTACGGGGTGCCATGCGTTCTGTGGTGTAACTTTATAGGTGTGCCCAACCGGTCACCGGCCCAGACGTGCTGCTAGCGTAATACAGGTCTGTTTCACGAGGTAAGACATACCTAAAGCTTAGCAGGCTGCATGTATTTAGTTTCCAATAACTGGTCTTGAACATTGCTTGCTTTGATCGATCGAGGCTACTATACCGACAACAACCGGTGGCTCGTATATCGGGAAAGTCAAGGGATTAGAGCTGCAAGCTGGCCTGCACTCAACTGACGTAAAACCCTGCAGACCCTAAAGGTATCCAGTCGGCCTTCCCATCTGATTACAACTAGCGCGGACTTCACGGGTTCCGCCTGATGTGGAAAATAGTTCCGACACTCAGATGAACCTAGAGTCGTTAGGTGTCGGGGGCAGCAGTTATGGTAAAACTTCACTAACCGTTCGTCGGCCGAGCTGGCACACCGGACACCTCATTTGGAATCAGTTTTGTCTTTAGGCCGTGAGCGGGCTCCCAAATGATACGGGGTGGGGACCAAGGCCGATGCAAATCCGAGTTTGCATGCCCGAATAGCTTAGGAGAGATGGGGGACCAGATGGAACGCGGTGGAACACCTACAGGGATGTCATAAGCTCGAAACGATATTGAATGTCTATTTATCGTTTGGCGGCGGTGTCCTATCGTTACCGTTCGAGCAAACTCACTGGACAATCTCTGTGCGCTTTTTGTGTGCGTGGTGAACGGGTGACCATCCGGTTGGTGGCCAGACAGCCGAGCGCGGGAGTTTTCACTTGAGTTCAGTTTACACC"

let complement c =
    match c with
    | 'A' -> 'T'
    | 'T' -> 'A'
    | 'C' -> 'G'
    | 'G' -> 'C'
    | x -> x

printfn "%s" (dataset 
    |> List.ofSeq 
    |> List.rev 
    |> List.map complement 
    |> List.fold (fun a x -> a + (string)x) "" 
    )